create table public.problems (
  rid integer generated by default as identity not null,
  user_id text null,
  "teamId" integer null,
  title text null,
  "pNum" text null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  constraint problems_pkey primary key (rid)
) TABLESPACE pg_default;