create table public.team (
  rid bigint generated by default as identity not null,
  "teamName" text null,
  description text null,
  "teamLeader" text null,
  "isActivated" smallint null,
  "UserList" text[] null,
  "createdAt" timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  solved integer null default 0,
  constraint team_pkey primary key (rid)
) TABLESPACE pg_default;