create table public."teamMission" (
  rid bigint generated by default as identity not null,
  "created_At" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  missions jsonb null,
  "solvedList" jsonb null,
  "teamId" integer null,
  difficulty text null,
  constraint teamMission_pkey primary key (rid)
) TABLESPACE pg_default;