create table if not exists public.team (
  rid bigint generated by default as identity not null,
  "teamName" text,
  description text,
  "teamLeader" text,
  "isActivated" smallint not null default 1,
  "UserList" text[],
  "createdAt" timestamptz not null default now(),
  solved integer not null default 0,
  constraint team_pkey primary key (rid)
);

alter table public.team
  add column if not exists "teamName" text,
  add column if not exists description text,
  add column if not exists "teamLeader" text,
  add column if not exists "isActivated" smallint not null default 1,
  add column if not exists "UserList" text[],
  add column if not exists "createdAt" timestamptz not null default now(),
  add column if not exists solved integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'team_isActivated_check'
      and conrelid = 'public.team'::regclass
  ) then
    alter table public.team
      add constraint "team_isActivated_check"
      check ("isActivated" in (0, 1));
  end if;
end;
$$;

create index if not exists team_createdAt_idx
on public.team ("createdAt" desc);

alter table public.team enable row level security;

drop policy if exists "team_select_members" on public.team;
drop policy if exists "team_select_public" on public.team;
create policy "team_select_public"
on public.team
for select
to anon, authenticated
using (true);

drop policy if exists "team_insert_authenticated" on public.team;
create policy "team_insert_authenticated"
on public.team
for insert
to authenticated
with check ((select auth.uid()) is not null);

drop policy if exists "team_update_leaders" on public.team;
create policy "team_update_leaders"
on public.team
for update
to authenticated
using (public.is_team_leader(rid, (select auth.uid())))
with check (public.is_team_leader(rid, (select auth.uid())));
