create table if not exists public."teamMission" (
  rid bigint generated by default as identity not null,
  "created_At" timestamptz not null default now(),
  missions jsonb,
  "solvedList" jsonb,
  "teamId" bigint,
  difficulty text,
  constraint teamMission_pkey primary key (rid)
);

alter table public."teamMission"
  add column if not exists "created_At" timestamptz not null default now(),
  add column if not exists missions jsonb,
  add column if not exists "solvedList" jsonb,
  add column if not exists "teamId" bigint,
  add column if not exists difficulty text;

alter table public."teamMission"
  alter column "teamId" type bigint using "teamId"::bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'teamMission_teamId_fkey'
      and conrelid = 'public."teamMission"'::regclass
  ) then
    alter table public."teamMission"
      add constraint "teamMission_teamId_fkey"
      foreign key ("teamId") references public.team (rid) on delete cascade;
  end if;
end;
$$;

create index if not exists teamMission_teamId_created_At_idx
on public."teamMission" ("teamId", "created_At" desc);

alter table public."teamMission" enable row level security;

drop policy if exists "teamMission_select_members" on public."teamMission";
create policy "teamMission_select_members"
on public."teamMission"
for select
to authenticated
using (public.is_team_member("teamId", (select auth.uid())));

drop policy if exists "teamMission_insert_members" on public."teamMission";
create policy "teamMission_insert_members"
on public."teamMission"
for insert
to authenticated
with check (public.is_team_member("teamId", (select auth.uid())));

drop policy if exists "teamMission_update_leaders" on public."teamMission";
create policy "teamMission_update_leaders"
on public."teamMission"
for update
to authenticated
using (public.is_team_leader("teamId", (select auth.uid())))
with check (public.is_team_leader("teamId", (select auth.uid())));
